apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a14afqfne-go 
  janus-idp.io/tekton: a14afqfne-go
  backstage.io/kubernetes-id: a14afqfne-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a14afqfne-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml